name: Bettershop_NPC
main: net.livecar.nuttyworks.bettershop_npcs.Bettershop_NPC
description: Provides and NPC for Bettershops
version: 1.0
depend: [Citizens,BetterShops]
author: Sir_Nutty@Spigot
commands:
  bsnpc:
    description: Configure the plugin with an NPC
    aliases: [bsn,bettershopnpc]
permissions:    
  bettershopnpc.interact:
     description: Allows a user to right click an NPC and open the shop
     default: true
  bettershopnpc.setshop:
     description: Allows a user to set the shop the NPC will open.
     default: false